Initial commit
utilant/ci_workflows pull request #1
Opened 2022-04-13 18:44 UTC by afrees-utilant

This PR contains the initial attempt at using reusable workflows. Unfortunately, these need to be stored in a public repo.

While the workflows themselves must be in a public repo (this one), the actual "meat" of the CI code is still private (see https://github.com/utilant/ci_runner/pull/24).

To see a test of these workflows in action, see https://github.com/utilant/ci-test-service/tree/testing-gh-actions. An example of how to use the workflows is given in the `example_workflows` directory.

2022-04-13 19:56 UTC, erogers-utilant requested changes

2022-04-13 19:56 UTC, erogers-utilant commented on .github/workflows/linting_testing.yml
> +  testing_39:
```suggestion
  testing_3_9:
```

2022-04-13 21:55 UTC, erogers-utilant requested changes

2022-04-13 21:55 UTC, erogers-utilant commented on .github/workflows/release_update_tag.yml
> +    runs-on: ubuntu-latest
Is there an advantage or requirement that leads us to run this workflow on GitHub-hosted runners?

2022-04-13 22:42 UTC, afrees-utilant commented on .github/workflows/release_update_tag.yml
> +    runs-on: ubuntu-latest
Yes, this is currently a requirement; as a security measure, currently our self-hosted runners do not have permissions to run workflows on any public repos.

The other workflows in this repo have `runs-on` as `self-hosted` because they are not actually used in this repo. This workflow (`release_update_tag.yml`) is the only one actually triggered by actions in the repo, namely cutting a new release (which currently only a member of the `utilant` organization can do).

Please keep the questions coming! I appreciate the careful look.

2022-04-18 20:55 UTC, erogers-utilant approved these changes
Looks great. Thanks!
🚢

2022-04-19 13:52 UTC, merged